# Detailed Data Description of Rechunked National Water Model v2.1 Retrospective Simulation
This notebook gives a *detailed* look at the metadata of the six Zarr stores which comprise the rechunked NWM v2.1 retrospective simulation. 
The perspective of the metadata is both from the `xarray.Dataset` point of view (as xarray would work with the data in memory) and from the Zarr point of view as well (storage, compression). Details are given at the dataset/group level and also for each variable. Also shown for each is the chunking scheme of a single input file (model output file), for comparison.

For a less detailed data description please see this 
[(html)](https://htmlpreview.github.io/?https://github.com/NCAR/rechunk\_retro_nwm\_v21/blob/main/notebooks/data_description.html) 
[(notebook)](https://htmlpreview.github.io/?https://github.com/NCAR/rechunk\_retro_nwm\_v21/blob/main/notebooks/data_description.ipynb).

In [1]:
from datetime import datetime
import numpy as np
import pandas as pd
import pathlib
import subprocess
import xarray as xr
import zarr as zr

/glade/work/jamesmcc/python_envs/379zr/lib/python3.7/site-packages/xarray/backends/cfgrib_.py:28: UserWarning: Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. Try `import cfgrib` to get the full error message
  "Failed to load cfgrib - most likely there is a problem accessing the ecCodes library. "


In [2]:
date = pd.to_datetime("1979-02-02")

input_dir = "/glade/scratch/zhangyx/WRF-Hydro/model.data.v2.1"
input_dir_precip = "/glade/scratch/jamesmcc/aorc_forcing_symlinks"
input_path = (
    f'{input_dir}/'
    f'{date.strftime("%Y")}/'
    f'{date.strftime("%Y%m%d%H%M")}')
input_path_precip = (
    f'{input_dir_precip}/'
    f'{date.strftime("%Y")}/'
    f'{date.strftime("%Y%m%d%H%M")}')

input_file_exs = {
    'chrtout': f'{input_path}.CHRTOUT_DOMAIN1.comp',
    'gwout': f'{input_path}.GWOUT_DOMAIN1.comp',
    'lakeout': f'{input_path}.LAKEOUT_DOMAIN1.comp',
    'ldasout': f'{input_path}.LDASOUT_DOMAIN1.comp',
    'rtout': f'{input_path}.RTOUT_DOMAIN1.comp',
    'precip': f'{input_path_precip}.LDASIN_DOMAIN1',
    }
assert all([pathlib.Path(ff).exists() for kk, ff in input_file_exs.items()])

Determine the output/zarr files. 

In [3]:
output_path_ishita = pathlib.Path("/glade/p/datashare/ishitas/nwm_retro_v2.1/")
output_path_james = pathlib.Path("/glade/p/datashare/jamesmcc/nwm_retro_v2.1/")

output_dict = {
    'lakeout': output_path_james / 'lakeout.zarr',
    'gwout': output_path_ishita / 'gwout.zarr',
    'chrtout': output_path_ishita / 'chrtout.zarr',
    'precip': output_path_james / 'precip.zarr',
    #'ldasout': output_path_ishita / 'ldasout.zarr',
    #'rtout': output_path_james / 'rtout.zarr',
    
}
assert all([ff.exists() for kk, ff in output_dict.items()])

This same report function will be applied to each dataset. 

In [4]:
def report(pattern):
    file_rechunked = output_dict[pattern]
    input_file_ex = input_file_exs[pattern]
    
    print(f"Output file report: {file_rechunked}")

    result = subprocess.run(
        f"du -shc {file_rechunked}", stdout=subprocess.PIPE, shell=True)
    file_size = result.stdout.decode("utf-8").split("\t")[0]
    print(f"Total file size: {file_size}")

    ds = xr.open_zarr(file_rechunked)
    dz = zr.open(file_rechunked)
    ds_src = xr.open_dataset(input_file_ex)
    
    print('')
    print("Dataset overviews:")
    
    print(f"xarray {pattern} SOURCE single file: ds.info")
    display(ds_src)
    
    print(f"xarray {pattern}: ds.info:")
    display(ds)

    print(f"zarr {pattern}: ds.info:")
    display(dz.info)
    
    print("Variable comparison xarray and zarr:")
    
    for vv in ds.variables:
        print(f"\n----------------------------------------------------------------------------------------------------------------")
        print(f"----------------------------------------------------------------------------------------------------------------\n")
        print(f"{pattern}: {vv}\n")
        
        if vv in ds_src.variables:
            print(f"xarray {pattern} SOURCE single file: ds[{vv}]:\n")
            display(ds_src[vv])
        else:
            print(f'{pattern}: {vv} not in source')        

        print(f"xarray {pattern}: ds[{vv}]:\n")
        display(ds[vv])

        print(f"")
        info = dz[vv].info
        print(f"zarr {pattern}:  dz[{vv}].info:")
        display(info)
        
        chunk_bytes = np.prod(info.obj.chunks) * info.obj.dtype.itemsize
        storage_ratio = float(str(info.obj._info_reporter).split(':')[-2].split('\n')[0].split(' ')[1])
        print(f"Un-Compressed Chunk size in MB: {chunk_bytes / 1048576}")
        print(f"   Compressed Chunk size in MB: {chunk_bytes / 1048576 / storage_ratio}")

    ds.close()
    ds_src.close()
        
    return None


## LAKEOUT: lake model output

In [5]:
report('lakeout')

Output file report: /glade/p/datashare/jamesmcc/nwm_retro_v2.1/lakeout.zarr
Total file size: 5.5G

Dataset overviews:
xarray lakeout SOURCE single file: ds.info


/glade/work/jamesmcc/python_envs/379zr/lib/python3.7/site-packages/xarray/backends/plugins.py:61: RuntimeWarning: Engine 'cfgrib' loading failed:
Cannot find the ecCodes library
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)


<xarray.Dataset>
Dimensions:                      (time: 1, reference_time: 1, feature_id: 5783)
Coordinates:
  * time                         (time) datetime64[ns] 1979-02-02
  * reference_time               (reference_time) datetime64[ns] 1979-02-01
  * feature_id                   (feature_id) int32 491 531 ... 1021092845
    latitude                     (feature_id) float32 ...
    longitude                    (feature_id) float32 ...
Data variables:
    crs                          |S1 ...
    reservoir_type               (feature_id) int32 ...
    reservoir_assimilated_value  (feature_id) float32 ...
    water_sfc_elev               (feature_id) float32 ...
    inflow                       (feature_id) float64 ...
    outflow                      (feature_id) float64 ...
Attributes:
    TITLE:                      OUTPUT FROM WRF-Hydro v5.2.0-beta2
    featureType:                timeSeries
    proj4:                      +proj=lcc +units=m +a=6370000.0 +b=6370000.0 ...
    model_initialization_time:  1979-02-01_00:00:00
    station_dimension:          lake_id
    model_output_valid_time:    1979-02-02_00:00:00
    model_total_valid_times:    1416
    Conventions:                CF-1.6
    code_version:               v5.2.0-beta2
    model_output_type:          reservoir
    model_configuration:        retrospective

xarray lakeout: ds.info:


<xarray.Dataset>
Dimensions:         (feature_id: 5783, time: 367439)
Coordinates:
  * feature_id      (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude        (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude       (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
  * time            (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T...
Data variables:
    crs             |S1 ...
    inflow          (time, feature_id) float64 dask.array<chunksize=(8064, 500), meta=np.ndarray>
    outflow         (time, feature_id) float64 dask.array<chunksize=(8064, 500), meta=np.ndarray>
    water_sfc_elev  (time, feature_id) float32 dask.array<chunksize=(8064, 500), meta=np.ndarray>
Attributes:
    Conventions:                  CF-1.6
    TITLE:                        OUTPUT FROM WRF-Hydro v5.2.0-beta2
    code_version:                 v5.2.0-beta2
    featureType:                  timeSeries
    model_configuration:          retrospective
    model_output_type:            reservoir
    proj4:                        +proj=lcc +units=m +a=6370000.0 +b=6370000....
    reservoir_assimilated_value:  Assimilation not performed
    reservoir_type:               1 = level pool everywhere
    station_dimension:            lake_id

zarr lakeout: ds.info:


Name        : /
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.DirectoryStore
No. members : 8
No. arrays  : 8
No. groups  : 0
Arrays      : crs, feature_id, inflow, latitude, longitude, outflow, time,
            : water_sfc_elev

Variable comparison xarray and zarr:

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: crs

xarray lakeout SOURCE single file: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes:
    transform_name:               latitude longitude
    grid_mapping_name:            latitude longitude
    esri_pe_string:               GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    spatial_ref:                  GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    long_name:                    CRS definition
    longitude_of_prime_meridian:  0.0
    _CoordinateAxes:              latitude longitude
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.5
    inverse_flattening:           298.25723

xarray lakeout: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes:
    _CoordinateAxes:              latitude longitude
    esri_pe_string:               GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    grid_mapping_name:            latitude longitude
    inverse_flattening:           298.2572326660156
    long_name:                    CRS definition
    longitude_of_prime_meridian:  0.0
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.5
    spatial_ref:                  GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    transform_name:               latitude longitude


zarr lakeout:  dz[crs].info:


Name               : /crs
Type               : zarr.core.Array
Data type          : |S1
Shape              : ()
Chunk shape        : ()
Order              : C
Read-only          : False
Compressor         : None
Store type         : zarr.storage.DirectoryStore
No. bytes          : 1
No. bytes stored   : 1077 (1.1K)
Storage ratio      : 0.0
Chunks initialized : 3/1

Un-Compressed Chunk size in MB: 9.5367431640625e-07
   Compressed Chunk size in MB: inf

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: feature_id

xarray lakeout SOURCE single file: ds[feature_id]:



/glade/work/jamesmcc/python_envs/379zr/lib/python3.7/site-packages/ipykernel_launcher.py:52: RuntimeWarning: divide by zero encountered in double_scalars


<xarray.DataArray 'feature_id' (feature_id: 5783)>
array([       491,        531,        747, ...,  947070203,  947070204,
       1021092845], dtype=int32)
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:  Lake ComID
    comment:    ComID from NHDPlusV2 waterbody layer
    cf_role:    timeseries_id

xarray lakeout: ds[feature_id]:



<xarray.DataArray 'feature_id' (feature_id: 5783)>
array([       491,        531,        747, ...,  947070203,  947070204,
       1021092845], dtype=int32)
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
Attributes:
    cf_role:    timeseries_id
    comment:    ComID from NHDPlusV2 waterbody layer
    long_name:  Lake ComID


zarr lakeout:  dz[feature_id].info:


Name               : /feature_id
Type               : zarr.core.Array
Data type          : int32
Shape              : (5783,)
Chunk shape        : (5783,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 23132 (22.6K)
No. bytes stored   : 13227 (12.9K)
Storage ratio      : 1.7
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 0.022060394287109375
   Compressed Chunk size in MB: 0.012976702521829045

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: inflow

xarray lakeout SOURCE single file: ds[inflow]:



<xarray.DataArray 'inflow' (feature_id: 5783)>
array([1.50000e-01, 4.00000e-02, 8.00000e-02, ..., 1.67590e+03, 1.77387e+03,
       1.82260e+02])
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:     Lake Inflow
    units:         m3 s-1
    grid_mapping:  crs
    valid_range:   [-1000000  1000000]

xarray lakeout: ds[inflow]:



<xarray.DataArray 'inflow' (time: 367439, feature_id: 5783)>
dask.array<open_dataset-fd8b16972b45e1dad0dd9bf62912480finflow, shape=(367439, 5783), dtype=float64, chunksize=(8064, 500), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    grid_mapping:  crs
    long_name:     Lake Inflow
    units:         m3 s-1


zarr lakeout:  dz[inflow].info:


Name               : /inflow
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 5783)
Chunk shape        : (8064, 500)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 8499598948 (7.9G)
No. bytes stored   : 1748449461 (1.6G)
Storage ratio      : 4.9
Chunks initialized : 552/552

Un-Compressed Chunk size in MB: 15.380859375
   Compressed Chunk size in MB: 3.138950892857143

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: latitude

xarray lakeout SOURCE single file: ds[latitude]:



<xarray.DataArray 'latitude' (feature_id: 5783)>
array([46.183273, 46.161163, 46.03409 , ..., 46.129097, 45.886326, 44.589592],
      dtype=float32)
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:      Lake latitude
    standard_name:  latitude
    units:          degrees_north

xarray lakeout: ds[latitude]:



<xarray.DataArray 'latitude' (feature_id: 5783)>
dask.array<open_dataset-fd8b16972b45e1dad0dd9bf62912480flatitude, shape=(5783,), dtype=float32, chunksize=(5783,), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
Attributes:
    long_name:      Lake latitude
    standard_name:  latitude
    units:          degrees_north


zarr lakeout:  dz[latitude].info:


Name               : /latitude
Type               : zarr.core.Array
Data type          : float32
Shape              : (5783,)
Chunk shape        : (5783,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 23132 (22.6K)
No. bytes stored   : 17498 (17.1K)
Storage ratio      : 1.3
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 0.022060394287109375
   Compressed Chunk size in MB: 0.01696953406700721

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: longitude

xarray lakeout SOURCE single file: ds[longitude]:



<xarray.DataArray 'longitude' (feature_id: 5783)>
array([ -68.379036,  -68.45489 ,  -68.064995, ..., -118.96537 , -119.657776,
        -73.30686 ], dtype=float32)
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:      Lake longitude
    standard_name:  longitude
    units:          degrees_east

xarray lakeout: ds[longitude]:



<xarray.DataArray 'longitude' (feature_id: 5783)>
dask.array<open_dataset-fd8b16972b45e1dad0dd9bf62912480flongitude, shape=(5783,), dtype=float32, chunksize=(5783,), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
Attributes:
    long_name:      Lake longitude
    standard_name:  longitude
    units:          degrees_east


zarr lakeout:  dz[longitude].info:


Name               : /longitude
Type               : zarr.core.Array
Data type          : float32
Shape              : (5783,)
Chunk shape        : (5783,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 23132 (22.6K)
No. bytes stored   : 17316 (16.9K)
Storage ratio      : 1.3
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 0.022060394287109375
   Compressed Chunk size in MB: 0.01696953406700721

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: outflow

xarray lakeout SOURCE single file: ds[outflow]:



<xarray.DataArray 'outflow' (feature_id: 5783)>
array([3.80000e-01, 1.30000e-01, 1.30000e-01, ..., 1.69247e+03, 1.78781e+03,
       2.22660e+02])
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:     Lake Outflow
    units:         m3 s-1
    grid_mapping:  crs
    valid_range:   [-1000000  1000000]

xarray lakeout: ds[outflow]:



<xarray.DataArray 'outflow' (time: 367439, feature_id: 5783)>
dask.array<open_dataset-fd8b16972b45e1dad0dd9bf62912480foutflow, shape=(367439, 5783), dtype=float64, chunksize=(8064, 500), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    grid_mapping:  crs
    long_name:     Lake Outflow
    units:         m3 s-1


zarr lakeout:  dz[outflow].info:


Name               : /outflow
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 5783)
Chunk shape        : (8064, 500)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 8499598948 (7.9G)
No. bytes stored   : 1246211282 (1.2G)
Storage ratio      : 6.8
Chunks initialized : 552/552

Un-Compressed Chunk size in MB: 15.380859375
   Compressed Chunk size in MB: 2.2618910845588234

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: time

xarray lakeout SOURCE single file: ds[time]:



<xarray.DataArray 'time' (time: 1)>
array(['1979-02-02T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-02
Attributes:
    long_name:      valid output time
    standard_name:  time
    valid_min:      4777980
    valid_max:      4862880

xarray lakeout: ds[time]:



<xarray.DataArray 'time' (time: 367439)>
array(['1979-02-01T01:00:00.000000000', '1979-02-01T02:00:00.000000000',
       '1979-02-01T03:00:00.000000000', ..., '2020-12-31T21:00:00.000000000',
       '2020-12-31T22:00:00.000000000', '2020-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:00:00
Attributes:
    long_name:      valid output time
    standard_name:  time
    valid_max:      4862880
    valid_min:      4777980


zarr lakeout:  dz[time].info:


Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (367439,)
Chunk shape        : (8064,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 2939512 (2.8M)
No. bytes stored   : 35841 (35.0K)
Storage ratio      : 82.0
Chunks initialized : 46/46

Un-Compressed Chunk size in MB: 0.0615234375
   Compressed Chunk size in MB: 0.0007502858231707317

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

lakeout: water_sfc_elev

xarray lakeout SOURCE single file: ds[water_sfc_elev]:



<xarray.DataArray 'water_sfc_elev' (feature_id: 5783)>
array([205.36955 , 247.18898 , 190.35312 , ..., 119.31217 ,  97.662834,
        41.705296], dtype=float32)
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 46.18 46.16 46.03 ... 46.13 45.89 44.59
    longitude   (feature_id) float32 -68.38 -68.45 -68.06 ... -119.7 -73.31
Attributes:
    long_name:  Water Surface Elevation
    units:      m
    comment:    If reservoir_type = 4, water_sfc_elev is invalid because this...

xarray lakeout: ds[water_sfc_elev]:



<xarray.DataArray 'water_sfc_elev' (time: 367439, feature_id: 5783)>
dask.array<open_dataset-fd8b16972b45e1dad0dd9bf62912480fwater_sfc_elev, shape=(367439, 5783), dtype=float32, chunksize=(8064, 500), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 491 531 747 ... 947070204 1021092845
    latitude    (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(5783,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    comment:    If reservoir_type = 4, water_sfc_elev is invalid because this...
    long_name:  Water Surface Elevation
    units:      m


zarr lakeout:  dz[water_sfc_elev].info:


Name               : /water_sfc_elev
Type               : zarr.core.Array
Data type          : float32
Shape              : (367439, 5783)
Chunk shape        : (8064, 500)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 8499598948 (7.9G)
No. bytes stored   : 2828358144 (2.6G)
Storage ratio      : 3.0
Chunks initialized : 552/552

Un-Compressed Chunk size in MB: 15.380859375
   Compressed Chunk size in MB: 5.126953125


## gwout file: groundwater model output

In [6]:
report('gwout')

Output file report: /glade/p/datashare/ishitas/nwm_retro_v2.1/gwout.zarr
Total file size: 1.7T

Dataset overviews:
xarray gwout SOURCE single file: ds.info


<xarray.Dataset>
Dimensions:         (time: 1, reference_time: 1, feature_id: 2776738)
Coordinates:
  * time            (time) datetime64[ns] 1979-02-02
  * reference_time  (reference_time) datetime64[ns] 1979-02-01
  * feature_id      (feature_id) int32 6635572 6635590 ... 25293410 15450136
Data variables:
    inflow          (feature_id) float64 ...
    outflow         (feature_id) float64 ...
    depth           (feature_id) float64 ...
Attributes:
    TITLE:                      OUTPUT FROM WRF-Hydro v5.2.0-beta2
    featureType:                timeSeries
    model_initialization_time:  1979-02-01_00:00:00
    station_dimension:          gw_id
    model_output_valid_time:    1979-02-02_00:00:00
    model_total_valid_times:    1416
    Conventions:                CF-1.6
    code_version:               v5.2.0-beta2
    model_output_type:          groundwater_rt
    model_configuration:        retrospective

xarray gwout: ds.info:


<xarray.Dataset>
Dimensions:     (time: 367439, feature_id: 2776738)
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Data variables:
    depth       (time, feature_id) float64 dask.array<chunksize=(672, 30000), meta=np.ndarray>
    inflow      (time, feature_id) float64 dask.array<chunksize=(672, 30000), meta=np.ndarray>
    outflow     (time, feature_id) float64 dask.array<chunksize=(672, 30000), meta=np.ndarray>
Attributes:
    Conventions:          CF-1.6
    TITLE:                OUTPUT FROM WRF-Hydro v5.2.0-beta2
    code_version:         v5.2.0-beta2
    featureType:          timeSeries
    model_configuration:  retrospective
    model_output_type:    groundwater_rt
    station_dimension:    gw_id

zarr gwout: ds.info:


Name        : /
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.DirectoryStore
No. members : 5
No. arrays  : 5
No. groups  : 0
Arrays      : depth, feature_id, inflow, outflow, time

Variable comparison xarray and zarr:

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

gwout: depth

xarray gwout SOURCE single file: ds[depth]:



<xarray.DataArray 'depth' (feature_id: 2776738)>
[2776738 values with dtype=float64]
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
Attributes:
    long_name:    Bucket Depth
    units:        mm
    valid_range:  [     0 100000]

xarray gwout: ds[depth]:



<xarray.DataArray 'depth' (time: 367439, feature_id: 2776738)>
dask.array<open_dataset-b5586199d0082e7918afd6a9e0edf1dddepth, shape=(367439, 2776738), dtype=float64, chunksize=(672, 30000), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    long_name:  Bucket Depth
    units:      mm


zarr gwout:  dz[depth].info:


Name               : /depth
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 2776738)
Chunk shape        : (672, 30000)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 4081127335928 (3.7T)
No. bytes stored   : 803056669519 (747.9G)
Storage ratio      : 5.1
Chunks initialized : 50871/50871

Un-Compressed Chunk size in MB: 76.904296875
   Compressed Chunk size in MB: 15.079273897058824

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

gwout: feature_id

xarray gwout SOURCE single file: ds[feature_id]:



<xarray.DataArray 'feature_id' (feature_id: 2776738)>
array([ 6635572,  6635590,  6635598, ..., 15448486, 25293410, 15450136],
      dtype=int32)
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
Attributes:
    long_name:  Groundwater Bucket ID
    comment:    Groundwater Bucket ID
    cf_role:    timeseries_id

xarray gwout: ds[feature_id]:



<xarray.DataArray 'feature_id' (feature_id: 2776738)>
array([ 6635572,  6635590,  6635598, ..., 15448486, 25293410, 15450136],
      dtype=int32)
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
Attributes:
    cf_role:    timeseries_id
    comment:    Groundwater Bucket ID
    long_name:  Groundwater Bucket ID


zarr gwout:  dz[feature_id].info:


Name               : /feature_id
Type               : zarr.core.Array
Data type          : int32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 4649079 (4.4M)
Storage ratio      : 2.4
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 4.413506189982097

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

gwout: inflow

xarray gwout SOURCE single file: ds[inflow]:



<xarray.DataArray 'inflow' (feature_id: 2776738)>
[2776738 values with dtype=float64]
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
Attributes:
    long_name:    Bucket Inflow
    units:        m3 s-1
    valid_range:  [       0 50000000]

xarray gwout: ds[inflow]:



<xarray.DataArray 'inflow' (time: 367439, feature_id: 2776738)>
dask.array<open_dataset-b5586199d0082e7918afd6a9e0edf1ddinflow, shape=(367439, 2776738), dtype=float64, chunksize=(672, 30000), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    long_name:  Bucket Inflow
    units:      m3 s-1


zarr gwout:  dz[inflow].info:


Name               : /inflow
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 2776738)
Chunk shape        : (672, 30000)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 4081127335928 (3.7T)
No. bytes stored   : 559740694318 (521.3G)
Storage ratio      : 7.3
Chunks initialized : 50871/50871

Un-Compressed Chunk size in MB: 76.904296875
   Compressed Chunk size in MB: 10.534835188356166

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

gwout: outflow

xarray gwout SOURCE single file: ds[outflow]:



<xarray.DataArray 'outflow' (feature_id: 2776738)>
[2776738 values with dtype=float64]
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
Attributes:
    long_name:    Bucket Outflow
    units:        m3 s-1
    valid_range:  [       0 50000000]

xarray gwout: ds[outflow]:



<xarray.DataArray 'outflow' (time: 367439, feature_id: 2776738)>
dask.array<open_dataset-b5586199d0082e7918afd6a9e0edf1ddoutflow, shape=(367439, 2776738), dtype=float64, chunksize=(672, 30000), chunktype=numpy.ndarray>
Coordinates:
  * feature_id  (feature_id) int32 6635572 6635590 6635598 ... 25293410 15450136
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    long_name:  Bucket Outflow
    units:      m3 s-1


zarr gwout:  dz[outflow].info:


Name               : /outflow
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 2776738)
Chunk shape        : (672, 30000)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 4081127335928 (3.7T)
No. bytes stored   : 457347197753 (425.9G)
Storage ratio      : 8.9
Chunks initialized : 50871/50871

Un-Compressed Chunk size in MB: 76.904296875
   Compressed Chunk size in MB: 8.640932233146067

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

gwout: time

xarray gwout SOURCE single file: ds[time]:



<xarray.DataArray 'time' (time: 1)>
array(['1979-02-02T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-02
Attributes:
    long_name:      valid output time
    standard_name:  time
    valid_min:      4777980
    valid_max:      4862880

xarray gwout: ds[time]:



<xarray.DataArray 'time' (time: 367439)>
array(['1979-02-01T01:00:00.000000000', '1979-02-01T02:00:00.000000000',
       '1979-02-01T03:00:00.000000000', ..., '2020-12-31T21:00:00.000000000',
       '2020-12-31T22:00:00.000000000', '2020-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:00:00
Attributes:
    long_name:      valid output time
    standard_name:  time
    valid_max:      4862880
    valid_min:      4777980


zarr gwout:  dz[time].info:


Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (367439,)
Chunk shape        : (672,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 2939512 (2.8M)
No. bytes stored   : 231171 (225.8K)
Storage ratio      : 12.7
Chunks initialized : 547/547

Un-Compressed Chunk size in MB: 0.005126953125
   Compressed Chunk size in MB: 0.00040369709645669296


## chrtout file: streamflow model output

In [7]:
report('chrtout')

Output file report: /glade/p/datashare/ishitas/nwm_retro_v2.1/chrtout.zarr
Total file size: 1.4T

Dataset overviews:
xarray chrtout SOURCE single file: ds.info


<xarray.Dataset>
Dimensions:         (time: 1, reference_time: 1, feature_id: 2776738)
Coordinates:
  * time            (time) datetime64[ns] 1979-02-02
  * reference_time  (reference_time) datetime64[ns] 1979-02-01
  * feature_id      (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude        (feature_id) float32 ...
    longitude       (feature_id) float32 ...
Data variables:
    crs             |S1 ...
    order           (feature_id) int32 ...
    elevation       (feature_id) float32 ...
    streamflow      (feature_id) float64 ...
    q_lateral       (feature_id) float64 ...
    velocity        (feature_id) float64 ...
    qSfcLatRunoff   (feature_id) float64 ...
    qBucket         (feature_id) float64 ...
    qBtmVertRunoff  (feature_id) float64 ...
Attributes: (12/18)
    TITLE:                      OUTPUT FROM WRF-Hydro v5.2.0-beta2
    featureType:                timeSeries
    proj4:                      +proj=lcc +units=m +a=6370000.0 +b=6370000.0 ...
    model_initialization_time:  1979-02-01_00:00:00
    station_dimension:          feature_id
    model_output_valid_time:    1979-02-02_00:00:00
    ...                         ...
    model_configuration:        retrospective
    dev_OVRTSWCRT:              1
    dev_NOAH_TIMESTEP:          3600
    dev_channel_only:           0
    dev_channelBucket_only:     0
    dev:                        dev_ prefix indicates development/internal me...

xarray chrtout: ds.info:


<xarray.Dataset>
Dimensions:     (feature_id: 2776738, time: 367439)
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Data variables:
    crs         |S1 ...
    streamflow  (time, feature_id) float64 dask.array<chunksize=(672, 30000), meta=np.ndarray>
    velocity    (time, feature_id) float64 dask.array<chunksize=(672, 30000), meta=np.ndarray>
Attributes:
    TITLE:                OUTPUT FROM WRF-Hydro v5.2.0-beta2
    code_version:         v5.2.0-beta2
    featureType:          timeSeries
    model_configuration:  retrospective
    proj4:                +proj=lcc +units=m +a=6370000.0 +b=6370000.0 +lat_1...

zarr chrtout: ds.info:


Name        : /
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.DirectoryStore
No. members : 10
No. arrays  : 10
No. groups  : 0
Arrays      : crs, elevation, feature_id, gage_id, latitude, longitude, order,
            : streamflow, time, velocity

Variable comparison xarray and zarr:

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: crs

xarray chrtout SOURCE single file: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes:
    transform_name:               latitude longitude
    grid_mapping_name:            latitude longitude
    esri_pe_string:               GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    spatial_ref:                  GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    long_name:                    CRS definition
    longitude_of_prime_meridian:  0.0
    _CoordinateAxes:              latitude longitude
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.5
    inverse_flattening:           298.25723

xarray chrtout: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes:
    _CoordinateAxes:              latitude longitude
    esri_pe_string:               GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    grid_mapping_name:            latitude longitude
    inverse_flattening:           298.2572326660156
    long_name:                    CRS definition
    longitude_of_prime_meridian:  0.0
    semi_major_axis:              6378137.0
    semi_minor_axis:              6356752.5
    spatial_ref:                  GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SP...
    transform_name:               latitude longitude


zarr chrtout:  dz[crs].info:


Name               : /crs
Type               : zarr.core.Array
Data type          : |S1
Shape              : ()
Chunk shape        : ()
Order              : C
Read-only          : False
Compressor         : None
Store type         : zarr.storage.DirectoryStore
No. bytes          : 1
No. bytes stored   : 1077 (1.1K)
Storage ratio      : 0.0
Chunks initialized : 3/1

Un-Compressed Chunk size in MB: 9.5367431640625e-07
   Compressed Chunk size in MB: inf

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: elevation

xarray chrtout SOURCE single file: ds[elevation]:



/glade/work/jamesmcc/python_envs/379zr/lib/python3.7/site-packages/ipykernel_launcher.py:52: RuntimeWarning: divide by zero encountered in double_scalars


<xarray.DataArray 'elevation' (feature_id: 2776738)>
[2776738 values with dtype=float32]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:      Feature Elevation
    standard_name:  Elevation
    units:          meters

xarray chrtout: ds[elevation]:



<xarray.DataArray 'elevation' (feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941efelevation, shape=(2776738,), dtype=float32, chunksize=(2776738,), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    long_name:  feature elevation
    units:      meters


zarr chrtout:  dz[elevation].info:


Name               : /elevation
Type               : zarr.core.Array
Data type          : float32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 8779076 (8.4M)
Storage ratio      : 1.3
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 8.148011427659254

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: feature_id

xarray chrtout SOURCE single file: ds[feature_id]:



<xarray.DataArray 'feature_id' (feature_id: 2776738)>
array([       101,        179,        181, ..., 1180001802, 1180001803,
       1180001804], dtype=int32)
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:  Reach ID
    comment:    NHDPlusv2 ComIDs within CONUS, arbitrary Reach IDs outside of...
    cf_role:    timeseries_id

xarray chrtout: ds[feature_id]:



<xarray.DataArray 'feature_id' (feature_id: 2776738)>
array([       101,        179,        181, ..., 1180001802, 1180001803,
       1180001804], dtype=int32)
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    cf_role:    timeseries_id
    comment:    NHDPlusv2 ComIDs within CONUS, arbitrary Reach IDs outside of...
    long_name:  Reach ID


zarr chrtout:  dz[feature_id].info:


Name               : /feature_id
Type               : zarr.core.Array
Data type          : int32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 795015 (776.4K)
Storage ratio      : 14.0
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 0.756601061139788

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: gage_id

chrtout: gage_id not in source
xarray chrtout: ds[gage_id]:



<xarray.DataArray 'gage_id' (feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941efgage_id, shape=(2776738,), dtype=|S15, chunksize=(2776738,), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    coordinates:  lat lon
    long_name:    NHD Gage Event ID from SOURCE_FEA field in Gages feature class


zarr chrtout:  dz[gage_id].info:


Name               : /gage_id
Type               : zarr.core.Array
Data type          : |S15
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 41651070 (39.7M)
No. bytes stored   : 488064 (476.6K)
Storage ratio      : 85.3
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 39.72155570983887
   Compressed Chunk size in MB: 0.46566888288205005

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: latitude

xarray chrtout SOURCE single file: ds[latitude]:



<xarray.DataArray 'latitude' (feature_id: 2776738)>
[2776738 values with dtype=float32]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:      Feature latitude
    standard_name:  latitude
    units:          degrees_north

xarray chrtout: ds[latitude]:



<xarray.DataArray 'latitude' (feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941eflatitude, shape=(2776738,), dtype=float32, chunksize=(2776738,), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    long_name:      feature latitude
    standard_name:  latitude
    units:          degrees_north


zarr chrtout:  dz[latitude].info:


Name               : /latitude
Type               : zarr.core.Array
Data type          : float32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 5866963 (5.6M)
Storage ratio      : 1.9
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 5.5749551873458065

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: longitude

xarray chrtout SOURCE single file: ds[longitude]:



<xarray.DataArray 'longitude' (feature_id: 2776738)>
[2776738 values with dtype=float32]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:      Feature longitude
    standard_name:  longitude
    units:          degrees_east

xarray chrtout: ds[longitude]:



<xarray.DataArray 'longitude' (feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941eflongitude, shape=(2776738,), dtype=float32, chunksize=(2776738,), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    long_name:      feature longitude
    standard_name:  longitude
    units:          degrees_east


zarr chrtout:  dz[longitude].info:


Name               : /longitude
Type               : zarr.core.Array
Data type          : float32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 6301787 (6.0M)
Storage ratio      : 1.8
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 5.884674919976129

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: order

xarray chrtout SOURCE single file: ds[order]:



<xarray.DataArray 'order' (feature_id: 2776738)>
[2776738 values with dtype=int32]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:      Streamflow Order
    standard_name:  order

xarray chrtout: ds[order]:



<xarray.DataArray 'order' (feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941eforder, shape=(2776738,), dtype=int32, chunksize=(2776738,), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
Attributes:
    long_name:  stream order


zarr chrtout:  dz[order].info:


Name               : /order
Type               : zarr.core.Array
Data type          : int32
Shape              : (2776738,)
Chunk shape        : (2776738,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 11106952 (10.6M)
No. bytes stored   : 1541885 (1.5M)
Storage ratio      : 7.2
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 10.592414855957031
   Compressed Chunk size in MB: 1.4711687299940321

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: streamflow

xarray chrtout SOURCE single file: ds[streamflow]:



<xarray.DataArray 'streamflow' (feature_id: 2776738)>
[2776738 values with dtype=float64]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:     River Flow
    units:         m3 s-1
    grid_mapping:  crs
    valid_range:   [      0 5000000]

xarray chrtout: ds[streamflow]:



<xarray.DataArray 'streamflow' (time: 367439, feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941efstreamflow, shape=(367439, 2776738), dtype=float64, chunksize=(672, 30000), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    grid_mapping:  crs
    long_name:     River Flow
    units:         m3 s-1


zarr chrtout:  dz[streamflow].info:


Name               : /streamflow
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 2776738)
Chunk shape        : (672, 30000)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 4081127335928 (3.7T)
No. bytes stored   : 754124414981 (702.3G)
Storage ratio      : 5.4
Chunks initialized : 50871/50871

Un-Compressed Chunk size in MB: 76.904296875
   Compressed Chunk size in MB: 14.241536458333332

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: time

xarray chrtout SOURCE single file: ds[time]:



<xarray.DataArray 'time' (time: 1)>
array(['1979-02-02T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-02
Attributes:
    long_name:      valid output time
    standard_name:  time
    valid_min:      4777980
    valid_max:      4862880

xarray chrtout: ds[time]:



<xarray.DataArray 'time' (time: 367439)>
array(['1979-02-01T01:00:00.000000000', '1979-02-01T02:00:00.000000000',
       '1979-02-01T03:00:00.000000000', ..., '2020-12-31T21:00:00.000000000',
       '2020-12-31T22:00:00.000000000', '2020-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:00:00
Attributes:
    long_name:      valid output time
    standard_name:  time


zarr chrtout:  dz[time].info:


Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (367439,)
Chunk shape        : (672,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 2939512 (2.8M)
No. bytes stored   : 231119 (225.7K)
Storage ratio      : 12.7
Chunks initialized : 547/547

Un-Compressed Chunk size in MB: 0.005126953125
   Compressed Chunk size in MB: 0.00040369709645669296

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

chrtout: velocity

xarray chrtout SOURCE single file: ds[velocity]:



<xarray.DataArray 'velocity' (feature_id: 2776738)>
[2776738 values with dtype=float64]
Coordinates:
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    latitude    (feature_id) float32 ...
    longitude   (feature_id) float32 ...
Attributes:
    long_name:     River Velocity
    units:         m s-1
    grid_mapping:  crs
    valid_range:   [      0 5000000]

xarray chrtout: ds[velocity]:



<xarray.DataArray 'velocity' (time: 367439, feature_id: 2776738)>
dask.array<open_dataset-5ee07aa6121226b4f24157a04a9941efvelocity, shape=(367439, 2776738), dtype=float64, chunksize=(672, 30000), chunktype=numpy.ndarray>
Coordinates:
    elevation   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * feature_id  (feature_id) int32 101 179 181 ... 1180001803 1180001804
    gage_id     (feature_id) |S15 dask.array<chunksize=(2776738,), meta=np.ndarray>
    latitude    (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    longitude   (feature_id) float32 dask.array<chunksize=(2776738,), meta=np.ndarray>
    order       (feature_id) int32 dask.array<chunksize=(2776738,), meta=np.ndarray>
  * time        (time) datetime64[ns] 1979-02-01T01:00:00 ... 2020-12-31T23:0...
Attributes:
    grid_mapping:  crs
    long_name:     River Velocity
    units:         m s-1


zarr chrtout:  dz[velocity].info:


Name               : /velocity
Type               : zarr.core.Array
Data type          : int32
Shape              : (367439, 2776738)
Chunk shape        : (672, 30000)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 4081127335928 (3.7T)
No. bytes stored   : 679656250705 (633.0G)
Storage ratio      : 6.0
Chunks initialized : 50871/50871

Un-Compressed Chunk size in MB: 76.904296875
   Compressed Chunk size in MB: 12.8173828125


## precip file: preciptation forcing file

In [8]:
report('precip')

Output file report: /glade/p/datashare/jamesmcc/nwm_retro_v2.1/precip.zarr
Total file size: 2.0T

Dataset overviews:
xarray precip SOURCE single file: ds.info


<xarray.Dataset>
Dimensions:         (time: 1, reference_time: 1, x: 4608, y: 3840)
Coordinates:
  * time            (time) datetime64[ns] 1979-02-02
  * reference_time  (reference_time) datetime64[ns] 1979-02-01
  * x               (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y               (y) float64 -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Data variables:
    crs             |S1 ...
    U2D             (time, y, x) float64 ...
    V2D             (time, y, x) float64 ...
    LWDOWN          (time, y, x) float64 ...
    RAINRATE        (time, y, x) float32 ...
    T2D             (time, y, x) float64 ...
    Q2D             (time, y, x) float64 ...
    PSFC            (time, y, x) float64 ...
    SWDOWN          (time, y, x) float64 ...
    LQFRAC          (time, y, x) float64 ...
Attributes:
    model_output_valid_time:    1979-02-02_00:00:00
    model_initialization_time:  1979-02-01_00:00:00
    NWM_version_number:         v2.1
    model_configuration:        AORC
    model_output_type:          forcing
    model_total_valid_times:    672.0

xarray precip: ds.info:


<xarray.Dataset>
Dimensions:   (time: 367440, y: 3840, x: 4608)
Coordinates:
  * time      (time) datetime64[ns] 1979-02-01 ... 2020-12-31T23:00:00
  * x         (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y         (y) float64 -1.92e+06 -1.919e+06 ... 1.918e+06 1.919e+06
Data variables:
    RAINRATE  (time, y, x) float32 dask.array<chunksize=(672, 350, 350), meta=np.ndarray>
    crs       |S1 ...
Attributes:
    NWM_version_number:   v2.1
    model_configuration:  AORC
    model_output_type:    forcing

zarr precip: ds.info:


Name        : /
Type        : zarr.hierarchy.Group
Read-only   : False
Store type  : zarr.storage.DirectoryStore
No. members : 5
No. arrays  : 5
No. groups  : 0
Arrays      : RAINRATE, crs, time, x, y

Variable comparison xarray and zarr:

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

precip: RAINRATE

xarray precip SOURCE single file: ds[RAINRATE]:



<xarray.DataArray 'RAINRATE' (time: 1, y: 3840, x: 4608)>
[17694720 values with dtype=float32]
Coordinates:
  * time     (time) datetime64[ns] 1979-02-02
  * x        (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y        (y) float64 -1.92e+06 -1.919e+06 -1.918e+06 ... 1.918e+06 1.919e+06
Attributes:
    cell_methods:    time: mean
    remap:           remapped via ESMF regrid_with_weights: Bilinear
    grid_mapping:    crs
    esri_pe_string:  PROJCS["Lambert_Conformal_Conic",GEOGCS["GCS_Sphere",DAT...
    proj4:           +proj=lcc +units=m +a=6370000.0 +b=6370000.0 +lat_1=30.0...
    units:           mm s^-1
    standard_name:   precipitation_flux
    long_name:       Surface Precipitation Rate

xarray precip: ds[RAINRATE]:



<xarray.DataArray 'RAINRATE' (time: 367440, y: 3840, x: 4608)>
dask.array<open_dataset-ac7d5a5c51e07dee1f3dcf4d0469c1dcRAINRATE, shape=(367440, 3840, 4608), dtype=float32, chunksize=(672, 350, 350), chunktype=numpy.ndarray>
Coordinates:
  * time     (time) datetime64[ns] 1979-02-01 ... 2020-12-31T23:00:00
  * x        (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
  * y        (y) float64 -1.92e+06 -1.919e+06 -1.918e+06 ... 1.918e+06 1.919e+06
Attributes:
    cell_methods:    time: mean
    esri_pe_string:  PROJCS["Lambert_Conformal_Conic",GEOGCS["GCS_Sphere",DAT...
    grid_mapping:    crs
    long_name:       Surface Precipitation Rate
    proj4:           +proj=lcc +units=m +a=6370000.0 +b=6370000.0 +lat_1=30.0...
    remap:           remapped via ESMF regrid_with_weights: Bilinear
    standard_name:   precipitation_flux
    units:           mm s^-1


zarr precip:  dz[RAINRATE].info:


Name               : /RAINRATE
Type               : zarr.core.Array
Data type          : float32
Shape              : (367440, 3840, 4608)
Chunk shape        : (672, 350, 350)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 26006991667200 (23.7T)
No. bytes stored   : 2184316757648 (2.0T)
Storage ratio      : 11.9
Chunks initialized : 84238/84238

Un-Compressed Chunk size in MB: 314.02587890625
   Compressed Chunk size in MB: 26.388729319852942

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

precip: crs

xarray precip SOURCE single file: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes: (12/17)
    transform_name:                 lambert_conformal_conic
    grid_mapping_name:              lambert_conformal_conic
    esri_pe_string:                 PROJCS["Lambert_Conformal_Conic",GEOGCS["...
    spatial_ref:                    PROJCS["Lambert_Conformal_Conic",GEOGCS["...
    long_name:                      CRS definition
    longitude_of_prime_meridian:    0.0
    ...                             ...
    latitude_of_projection_origin:  40.0
    false_easting:                  0.0
    false_northing:                 0.0
    earth_radius:                   6370000.0
    semi_major_axis:                6370000.0
    inverse_flattening:             0.0

xarray precip: ds[crs]:



<xarray.DataArray 'crs' ()>
array(b'', dtype='|S1')
Attributes: (12/17)
    GeoTransform:                   -2303999.17655 1000.0 0 1919999.66329 0 -...
    _CoordinateAxes:                y x
    _CoordinateTransformType:       Projection
    earth_radius:                   6370000.0
    esri_pe_string:                 PROJCS["Lambert_Conformal_Conic",GEOGCS["...
    false_easting:                  0.0
    ...                             ...
    longitude_of_central_meridian:  -97.0
    longitude_of_prime_meridian:    0.0
    semi_major_axis:                6370000.0
    spatial_ref:                    PROJCS["Lambert_Conformal_Conic",GEOGCS["...
    standard_parallel:              [30.0, 60.0]
    transform_name:                 lambert_conformal_conic


zarr precip:  dz[crs].info:


Name               : /crs
Type               : zarr.core.Array
Data type          : |S1
Shape              : ()
Chunk shape        : ()
Order              : C
Read-only          : False
Compressor         : None
Store type         : zarr.storage.DirectoryStore
No. bytes          : 1
No. bytes stored   : 1970 (1.9K)
Storage ratio      : 0.0
Chunks initialized : 3/1

Un-Compressed Chunk size in MB: 9.5367431640625e-07
   Compressed Chunk size in MB: inf

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

precip: time

xarray precip SOURCE single file: ds[time]:



/glade/work/jamesmcc/python_envs/379zr/lib/python3.7/site-packages/ipykernel_launcher.py:52: RuntimeWarning: divide by zero encountered in double_scalars


<xarray.DataArray 'time' (time: 1)>
array(['1979-02-02T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-02
Attributes:
    standard_name:  time
    long_name:      valid output time

xarray precip: ds[time]:



<xarray.DataArray 'time' (time: 367440)>
array(['1979-02-01T00:00:00.000000000', '1979-02-01T01:00:00.000000000',
       '1979-02-01T02:00:00.000000000', ..., '2020-12-31T21:00:00.000000000',
       '2020-12-31T22:00:00.000000000', '2020-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1979-02-01 ... 2020-12-31T23:00:00
Attributes:
    long_name:      valid output time
    standard_name:  time


zarr precip:  dz[time].info:


Name               : /time
Type               : zarr.core.Array
Data type          : int64
Shape              : (367440,)
Chunk shape        : (672,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 2939520 (2.8M)
No. bytes stored   : 231110 (225.7K)
Storage ratio      : 12.7
Chunks initialized : 547/547

Un-Compressed Chunk size in MB: 0.005126953125
   Compressed Chunk size in MB: 0.00040369709645669296

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

precip: x

xarray precip SOURCE single file: ds[x]:



<xarray.DataArray 'x' (x: 4608)>
array([-2303499.25, -2302499.25, -2301499.25, ...,  2301500.75,  2302500.75,
        2303500.75])
Coordinates:
  * x        (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
Attributes:
    standard_name:        projection_x_coordinate
    long_name:            x coordinate of projection
    units:                m
    _CoordinateAxisType:  GeoX
    resolution:           1000.0

xarray precip: ds[x]:



<xarray.DataArray 'x' (x: 4608)>
array([-2303499.25, -2302499.25, -2301499.25, ...,  2301500.75,  2302500.75,
        2303500.75])
Coordinates:
  * x        (x) float64 -2.303e+06 -2.302e+06 ... 2.303e+06 2.304e+06
Attributes:
    _CoordinateAxisType:  GeoX
    long_name:            x coordinate of projection
    resolution:           1000.0
    standard_name:        projection_x_coordinate
    units:                m


zarr precip:  dz[x].info:


Name               : /x
Type               : zarr.core.Array
Data type          : float64
Shape              : (4608,)
Chunk shape        : (4608,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 36864 (36.0K)
No. bytes stored   : 6753 (6.6K)
Storage ratio      : 5.5
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 0.03515625
   Compressed Chunk size in MB: 0.006392045454545455

----------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------

precip: y

xarray precip SOURCE single file: ds[y]:



<xarray.DataArray 'y' (y: 3840)>
array([-1919500.375, -1918500.375, -1917500.375, ...,  1917499.625,
        1918499.625,  1919499.625])
Coordinates:
  * y        (y) float64 -1.92e+06 -1.919e+06 -1.918e+06 ... 1.918e+06 1.919e+06
Attributes:
    standard_name:        projection_y_coordinate
    long_name:            y coordinate of projection
    units:                m
    _CoordinateAxisType:  GeoY
    resolution:           1000.0

xarray precip: ds[y]:



<xarray.DataArray 'y' (y: 3840)>
array([-1919500.375, -1918500.375, -1917500.375, ...,  1917499.625,
        1918499.625,  1919499.625])
Coordinates:
  * y        (y) float64 -1.92e+06 -1.919e+06 -1.918e+06 ... 1.918e+06 1.919e+06
Attributes:
    _CoordinateAxisType:  GeoY
    long_name:            y coordinate of projection
    resolution:           1000.0
    standard_name:        projection_y_coordinate
    units:                m


zarr precip:  dz[y].info:


Name               : /y
Type               : zarr.core.Array
Data type          : float64
Shape              : (3840,)
Chunk shape        : (3840,)
Order              : C
Read-only          : False
Compressor         : Blosc(cname='lz4', clevel=5, shuffle=SHUFFLE, blocksize=0)
Store type         : zarr.storage.DirectoryStore
No. bytes          : 30720 (30.0K)
No. bytes stored   : 5679 (5.5K)
Storage ratio      : 5.4
Chunks initialized : 1/1

Un-Compressed Chunk size in MB: 0.029296875
   Compressed Chunk size in MB: 0.005425347222222222


## ldasout file: NoahMP land surface model output

In [9]:
# report('ldasout')

## rtout: overland and subsruface model routing output

In [10]:
# report('rtout')